const IP_FACTORY_BASE_URL = "https://ip.ipgongchang.xin"
const API_BASE_URL = IP_FACTORY_BASE_URL

const REQUEST_TIMEOUT = 60000
const VOICE_COACH_MP_STREAM_ENABLED = false

module.exports = {
  API_BASE_URL,
  IP_FACTORY_BASE_URL,
  REQUEST_TIMEOUT,
  VOICE_COACH_MP_STREAM_ENABLED,
}
