const IP_FACTORY_BASE_URL = "https://ip.ipgongchang.xin"
const DIRECT_API_BASE_URL = "https://www.ipnrgc.com"
const VOICE_COACH_HTTP_BASE_URL = IP_FACTORY_BASE_URL
const VOICE_COACH_WS_BASE_URL = IP_FACTORY_BASE_URL
const API_BASE_URL = IP_FACTORY_BASE_URL
const API_BASE_URLS = [IP_FACTORY_BASE_URL, DIRECT_API_BASE_URL]
const AUTH_BASE_URLS = API_BASE_URLS

const REQUEST_TIMEOUT = 240000

module.exports = {
  API_BASE_URL,
  API_BASE_URLS,
  AUTH_BASE_URLS,
  DIRECT_API_BASE_URL,
  IP_FACTORY_BASE_URL,
  VOICE_COACH_HTTP_BASE_URL,
  VOICE_COACH_WS_BASE_URL,
  REQUEST_TIMEOUT,
}
