const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = process.cwd()
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), "utf8")

const listRoute = () => read("app", "api", "app", "knowledge-spaces", "route.ts")
const catchAllRoute = () => read("app", "api", "app", "knowledge-spaces", "[...path]", "route.ts")

test("APP knowledge-spaces list route is an auth-protected read-only RDS facade", () => {
  const source = listRoute()

  assert.match(source, /export const runtime = "nodejs"/)
  assert.match(source, /export async function GET\(request: NextRequest\)/)
  assert.match(source, /resolveAliyunRdsAppAuthUser\(request\)/)
  assert.match(source, /appAuthRequiredResponse\(\)/)
  assert.match(source, /getAliyunRdsAppAccountContext\(auth\.user\)/)
  assert.match(source, /accountContextPayload\(ctx\)/)
  assert.match(source, /from public\.mp_knowledge_spaces space/)
  assert.match(source, /from public\.mp_knowledge_space_access access/)
  assert.match(source, /space\.status = 'active'/)
  assert.match(source, /tenant_scope_denied/)
  assert.match(source, /space\.company_id = \$2::uuid/)
  assert.match(source, /space\.store_id = \$3::uuid/)
  assert.match(source, /access\.user_id = \$4::uuid/)
  assert.match(source, /knowledge_spaces_schema_not_ready/)
  assert.match(source, /knowledge_space_manifest_not_ready/)
  assert.match(source, /const spaces = result\.rows\.map\(summaryFromRow\)\.filter\(isKnowledgeSpaceSummary\)/)
  assert.match(source, /spaces,/)
  assert.doesNotMatch(source, /insert into/i)
  assert.doesNotMatch(source, /update public\./i)
  assert.doesNotMatch(source, /delete from/i)
  assert.doesNotMatch(source, /export async function POST/)
  assert.doesNotMatch(source, /generateXhs|generatePrivateCopy|poster/i)
  assert.doesNotMatch(source, /wechatpay|IAP|chargeMpAiPoints/i)
})

test("APP knowledge-spaces detail facade serves only real manifests and never local fixture fallback", () => {
  const source = catchAllRoute()

  assert.match(source, /export const runtime = "nodejs"/)
  assert.match(source, /export async function GET\(/)
  assert.match(source, /params: Promise<\{ path\?: string\[\] \}>/)
  assert.match(source, /resolveAliyunRdsAppAuthUser\(request\)/)
  assert.match(source, /appAuthRequiredResponse\(\)/)
  assert.match(source, /getAliyunRdsAppAccountContext\(auth\.user\)/)
  assert.match(source, /accountContextPayload\(ctx\)/)
  assert.match(source, /from public\.mp_knowledge_spaces space/)
  assert.match(source, /from public\.mp_knowledge_space_access access/)
  assert.match(source, /space\.metadata_json->'app_manifest'->>'id' = \$5/)
  assert.match(source, /space\.metadata_json->'knowledge_manifest'->>'id' = \$5/)
  assert.match(source, /space\.metadata_json->'manifest'->>'id' = \$5/)
  assert.match(source, /manbeilian_store_knowledge_v1/)
  assert.match(source, /knowledge_space_manifest_not_ready/)
  assert.match(source, /knowledge_spaces_schema_not_ready/)
  assert.doesNotMatch(source, /manbeilian-space\.generated\.json/)
  assert.doesNotMatch(source, /fixtures\/knowledge/)
  assert.doesNotMatch(source, /LOCAL_SPACES/)
  assert.doesNotMatch(source, /export async function POST/)
  assert.doesNotMatch(source, /export async function PUT/)
  assert.doesNotMatch(source, /export async function DELETE/)
})

test("APP knowledge-spaces catch-all maps space, group, and card GET paths to App client response shapes", () => {
  const source = catchAllRoute()

  assert.match(source, /\[spaceId, groupsSegment, groupId, cardsSegment, cardId\] = segments/)
  assert.match(source, /\!\[1, 3, 5\]\.includes\(segments\.length\)/)
  assert.match(source, /groupsSegment !== "groups"/)
  assert.match(source, /cardsSegment !== "cards"/)
  assert.match(source, /space: manifest/)
  assert.match(source, /const group = findGroup\(manifest, groupId\)/)
  assert.match(source, /group,/)
  assert.match(source, /const card = findCard\(group, cardId\)/)
  assert.match(source, /card,/)
  assert.match(source, /knowledge_space_not_found/)
  assert.match(source, /knowledge_group_not_found/)
  assert.match(source, /knowledge_card_not_found/)
})
