const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = process.cwd()
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), "utf8")

test("Aliyun domain readiness uses public DoH while retaining local DNS pollution diagnostics", () => {
  const source = read("scripts", "check-aliyun-domain-readiness.mjs")

  assert.match(source, /PUBLIC_DOH_RESOLVERS/)
  assert.match(source, /async function resolvePublicDoh/)
  assert.match(source, /function normalizeDohPayload/)
  assert.match(source, /evidenceSource: usePublicDoh \? "public_doh" : "local_resolver"/)
  assert.match(source, /localResolver/)
  assert.match(source, /pollutedBySpecialUse/)
  assert.match(source, /httpsProbe\(url\.parsed, target\.probePath, args\.timeoutMs, dns\)/)
  assert.match(source, /async function resolveWildcardDns/)
  assert.match(source, /function baseDomainFromHostname/)
  assert.match(source, /wildcard-proof-\$\{nonce\}\.\$\{baseDomain\}/)
  assert.match(source, /wildcardProbe/)
  assert.match(source, /dns_special_use_wildcard_ip/)
  assert.match(source, /198\.18\.0\.0\/15/)
  assert.match(source, /function buildDomainCutoverPlan/)
  assert.match(source, /api_sae_custom_domain/)
  assert.match(source, /asset_cdn_custom_domain/)
  assert.match(source, /asset_oss_custom_domain/)
  assert.match(source, /certificateId/)
  assert.match(source, /icpEvidence/)
  assert.match(source, /domainCutoverPlan/)
})

test("Aliyun domain readiness exposes P07 non-secret cutover writeback fields", () => {
  const source = read("scripts", "check-aliyun-domain-readiness.mjs")

  assert.match(source, /items\.apiDomainHttps/)
  assert.match(source, /items\.assetDomainHttps/)
  assert.match(source, /recordValue/)
  assert.match(source, /api_sae_custom_domain/)
  assert.match(source, /asset_cdn_custom_domain/)
  assert.match(source, /asset_oss_custom_domain/)
  assert.match(source, /httpsProbeUrl: `https:\/\/\$\{EXPECTED_API_HOST\}\/api\/healthz`/)
  assert.match(source, /httpsProbeUrl: `https:\/\/\$\{EXPECTED_ASSET_HOST\}\/`/)
  assert.match(source, /Public DoH resolves api-cn to the Aliyun public ingress/)
  assert.match(source, /Public DoH resolves assets-cn to the selected OSS\/CDN asset endpoint/)
})

test("Aliyun deployment docs record current DoH-based P07 state", () => {
  const deployDoc = read("docs", "DEPLOY_ALIYUN_PRODUCTION_CN.md")
  const releaseManifest = read("docs", "release-manifest-2026-06-21-app-aliyun-production-cn-bridge.md")

  assert.match(deployDoc, /DoH 显示 `api-cn\.ipgongchang\.xin -> 47\.111\.169\.95`/)
  assert.match(deployDoc, /`assets-cn\.ipgongchang\.xin -> 47\.111\.169\.95`/)
  assert.match(deployDoc, /`icpReady` 和域名组 `confirmed` 仍保持 false/)
  assert.match(deployDoc, /本机 `dig` 返回的 `198\.18\.\*` 是当前本机网络\/代理解析污染提示/)
  assert.match(releaseManifest, /当前 DoH 结果为 `api-cn\.ipgongchang\.xin -> 47\.111\.169\.95`/)
  assert.match(releaseManifest, /`assets-cn\.ipgongchang\.xin -> 47\.111\.169\.95`/)
  assert.match(releaseManifest, /targetReady=2\/2/)
  assert.match(releaseManifest, /localResolver\.pollutedBySpecialUse/)
})

test("Aliyun domain docs reject legacy api/ip records as APP production-cn evidence", () => {
  const deployDoc = read("docs", "DEPLOY_ALIYUN_PRODUCTION_CN.md")
  const checklist = read("docs", "app-production-cn-env-checklist.md")
  const releaseManifest = read("docs", "release-manifest-2026-06-21-app-aliyun-production-cn-bridge.md")

  assert.match(deployDoc, /106\.14\.241\.129[\s\S]{0,120}不能作为 APP production-cn/)
  assert.match(checklist, /106\.14\.241\.129[\s\S]{0,120}不能作为 `api-cn`/)
  assert.match(releaseManifest, /旧 `api` \/ `ip` A 记录指向 `106\.14\.241\.129`[\s\S]{0,120}不能复用为 APP production-cn/)
})
