const test = require("node:test")
const assert = require("node:assert/strict")
const { execFileSync } = require("node:child_process")
const fs = require("node:fs")
const os = require("node:os")
const path = require("node:path")

const root = process.cwd()
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), "utf8")
const readJson = (...parts) => JSON.parse(read(...parts))

test("Aliyun console runbook command is wired into scripts and predeploy", () => {
  const pkg = readJson("package.json")
  const predeploy = read("scripts", "aliyun-predeploy-commands.mjs")
  const releaseArtifacts = read("scripts", "prepare-aliyun-release-artifacts.mjs")
  const deploySpec = readJson("deploy", "aliyun-production-cn.example.json")

  assert.equal(pkg.scripts["aliyun:console:runbook"], "node ./scripts/generate-aliyun-console-runbook.mjs")
  assert.equal(pkg.scripts["aliyun:console:runbook:test"], "node --test tests/aliyun-console-runbook.static.test.js")
  assert.match(predeploy, /aliyun:console:runbook:test/)
  assert.match(predeploy, /aliyun:console:runbook/)
  assert.ok(deploySpec.localPredeployChecks.includes("corepack pnpm run aliyun:console:runbook:test"))
  assert.ok(deploySpec.localPredeployChecks.includes("corepack pnpm run aliyun:console:runbook"))
  assert.ok(deploySpec.predeployChecks.includes("corepack pnpm aliyun:console:runbook"))
  assert.match(releaseArtifacts, /canStartNowConsoleTasks/)
  assert.match(releaseArtifacts, /readyActionPackets/)
  assert.match(releaseArtifacts, /blockedByTaskDependencies/)
  assert.match(releaseArtifacts, /consoleClosureBrief/)
  assert.match(releaseArtifacts, /blockedCredentialCount/)
  assert.match(releaseArtifacts, /resourceEvidenceReady/)
  assert.match(releaseArtifacts, /partiallyObservedResourceEvidenceIds/)
})

test("Aliyun console runbook renders current console fields without secret values", () => {
  const output = execFileSync(process.execPath, ["scripts/generate-aliyun-console-runbook.mjs"], {
    cwd: root,
    encoding: "utf8",
    maxBuffer: 1024 * 1024 * 40,
  })
  const report = JSON.parse(output)
  const ids = report.consoleTasks.map((item) => item.id)
  const sae = report.consoleTasks.find((item) => item.id === "C01_SAE_RUNTIME")
  const acr = report.consoleTasks.find((item) => item.id === "C02_ACR_IMAGE_AND_PULL")
  const apiDomain = report.consoleTasks.find((item) => item.id === "C03_API_DOMAIN_HTTPS_ICP")
  const assetDomain = report.consoleTasks.find((item) => item.id === "C04_ASSET_DOMAIN_HTTPS_ICP")
  const oss = report.consoleTasks.find((item) => item.id === "C05_OSS_AUDIO_RAM_STS")
  const env = report.consoleTasks.find((item) => item.id === "C06_ENV_IMPORT")
  const readyPacketIds = report.readyActionPackets.map((item) => item.taskId)

  assert.equal(report.ok, true)
  assert.equal(report.containsValues, false)
  assert.equal(report.mutationPerformed, false)
  assert.equal(report.readOnlyOnly, true)
  assert.equal(report.currentScope, "backend_aliyun_only")
  assert.equal(report.canProceedWithoutWechat, true)
  assert.equal(report.secretLeakCheck.ok, true)
  assert.deepEqual(ids, [
    "C01_SAE_RUNTIME",
    "C02_ACR_IMAGE_AND_PULL",
    "C03_API_DOMAIN_HTTPS_ICP",
    "C04_ASSET_DOMAIN_HTTPS_ICP",
    "C05_OSS_AUDIO_RAM_STS",
    "C06_ENV_IMPORT",
    "C07_SLS_ALERTS",
  ])
  assert.equal(report.target.region, "cn-hangzhou")
  assert.equal(report.target.appName, "meiye-huajing-app-api-production-cn")
  assert.deepEqual(report.summary.requiredBlocking, [])
  assert.ok(report.summary.deferredAppLaunchBlocking.includes("WECHAT_OPEN_APP_ID"))
  assert.ok(report.summary.deferredAppLaunchBlocking.includes("WECHAT_OPEN_APP_SECRET"))
  assert.ok(report.summary.deferredAppLaunchBlocking.includes("APPLE_TEAM_ID"))
  assert.equal(report.summary.currentScope, "backend_aliyun_only")
  assert.equal(report.summary.canProceedWithoutWechat, true)
  assert.deepEqual(report.summary.blockedUserActionIds, ["U09_DEPLOY_AUTHORIZATION"])
  assert.deepEqual(report.summary.canStartNowConsoleTasks, [])
  assert.equal(report.summary.readyActionPackets, 0)
  assert.equal(report.summary.blockedCredentialCount, 0)
  assert.equal(report.summary.readySecretEnvVariableCount, 0)
  assert.equal(report.summary.resourceEvidenceReady, "7/7")
  assert.deepEqual(report.summary.blockedResourceEvidenceIds, [])
  assert.deepEqual(report.summary.partiallyObservedResourceEvidenceIds, [])
  assert.equal(report.consoleClosureBrief.currentScope, "backend_aliyun_only")
  assert.equal(report.consoleClosureBrief.canProceedWithoutWechat, true)
  assert.match(report.consoleClosureBrief.conclusion, /U09_DEPLOY_AUTHORIZATION/)
  assert.match(report.consoleClosureBrief.conclusion, /404 清零验收/)
  assert.equal(report.consoleClosureBrief.blockedCredentialCount, 0)
  assert.deepEqual(report.consoleClosureBrief.blockedCredentialNames, [])
  assert.ok(report.consoleClosureBrief.deferredAppLaunchBlocking.includes("WECHAT_OPEN_APP_ID"))
  assert.ok(report.consoleClosureBrief.deferredAppLaunchBlocking.includes("WECHAT_OPEN_APP_SECRET"))
  assert.equal(report.consoleClosureBrief.readySecretEnvVariableCount, 0)
  assert.equal(report.consoleClosureBrief.resourceEvidenceReady, "7/7")
  assert.deepEqual(report.consoleClosureBrief.blockedResourceEvidenceIds, [])
  assert.deepEqual(report.consoleClosureBrief.partiallyObservedResourceEvidenceIds, [])
  assert.deepEqual(report.consoleClosureBrief.canStartNowConsoleTasks, [])
  assert.deepEqual(report.consoleClosureBrief.readyActionPacketIds, [])
  assert.deepEqual(report.consoleClosureBrief.nextActionTimeConfirmations, [])
  assert.deepEqual(report.consoleClosureBrief.blockedResourceEvidence, [])
  assert.deepEqual(readyPacketIds, [])
  assert.deepEqual(report.summary.blockedByTaskDependencies, [])
  assert.equal(sae.sequencePhase, "runtime")
  assert.deepEqual(sae.dependsOn, ["C02_ACR_IMAGE_AND_PULL", "C05_OSS_AUDIO_RAM_STS", "C06_ENV_IMPORT"])
  assert.deepEqual(sae.blockingDependencies, [])
  assert.equal(sae.canStartNow, false)
  assert.ok(sae.targetFields.some((item) => item.name === "containerPort" && item.value === 3000))
  assert.deepEqual(sae.currentBlockers, [])
  assert.equal(acr.requiresActionTimeConfirmation, true)
  assert.equal(acr.sequencePhase, "image_runtime")
  assert.deepEqual(acr.dependsOn, [])
  assert.deepEqual(acr.blockingDependencies, [])
  assert.equal(acr.canStartNow, false)
  assert.equal(acr.currentActionScope, "image_push_or_import_and_digest_verification")
  assert.ok(acr.deferredActions.some((item) => item.includes("不购买 ACR")))
  assert.ok(acr.deferredActions.some((item) => item.includes("不部署 production-cn")))
  assert.ok(acr.targetFields.some((item) => item.name === "remoteDigest" && /^sha256:[a-f0-9]{64}$/.test(String(item.value))))
  assert.ok(acr.targetFields.some((item) => item.name === "localDigest" && String(item.value).length > 0))
  assert.ok(acr.currentEvidence.includes("acr.purchaseCandidate.requiresActionTimePurchaseConfirmation=false"))
  assert.ok(acr.completionEvidence.includes("corepack pnpm aliyun:image:plan:strict pass"))
  assert.equal(oss.canStartNow, false)
  assert.deepEqual(oss.currentBlockers, [])
  assert.ok(oss.completionEvidence.includes("ramLeastPrivilege=true"))
  assert.deepEqual(apiDomain.dependsOn, ["C01_SAE_RUNTIME"])
  assert.deepEqual(apiDomain.blockingDependencies, [])
  assert.equal(apiDomain.canStartNow, false)
  assert.ok(apiDomain.targetFields.some((item) => item.name === "notAccepted" && /106\.14\.241\.129/.test(String(item.value))))
  assert.deepEqual(assetDomain.dependsOn, ["C05_OSS_AUDIO_RAM_STS"])
  assert.deepEqual(assetDomain.blockingDependencies, [])
  assert.equal(assetDomain.canStartNow, false)
  assert.ok(assetDomain.targetFields.some((item) => item.name === "notAccepted" && /106\.14\.241\.129/.test(String(item.value))))
  assert.deepEqual(env.dependsOn, ["C05_OSS_AUDIO_RAM_STS"])
  assert.deepEqual(env.blockingDependencies, [])
  assert.equal(env.canStartNow, false)
  assert.ok(env.targetFields.some((item) => item.name === "secretNotInImage" && item.value === true))
  assert.deepEqual(env.currentBlockers, [])
  assert.match(report.currentAnswer, /U09_DEPLOY_AUTHORIZATION/)
  assert.doesNotMatch(report.currentAnswer, /必须先补齐微信开放平台移动 App 凭证/)
  assert.doesNotMatch(JSON.stringify(report.summary.requiredBlocking), /WECHAT_OPEN_APP_ID|WECHAT_OPEN_APP_SECRET|APPLE_TEAM_ID/)
  assert.doesNotMatch(output, /sk-[A-Za-z0-9_-]{20,}/)
  assert.doesNotMatch(output, /LTAI[A-Za-z0-9]{12,}/)
  assert.doesNotMatch(output, /:\/\/[^\s:@]+:[^\s@]+@/)
})

test("Aliyun console runbook markdown includes action packets and completion evidence", () => {
  const tmpdir = fs.mkdtempSync(path.join(os.tmpdir(), "aliyun-console-runbook-"))
  const markdownPath = path.join(tmpdir, "console-runbook.md")
  const output = execFileSync(process.execPath, [
    "scripts/generate-aliyun-console-runbook.mjs",
    "--markdown",
    markdownPath,
  ], {
    cwd: root,
    encoding: "utf8",
    maxBuffer: 1024 * 1024 * 40,
  })
  const markdown = fs.readFileSync(markdownPath, "utf8")

  assert.match(markdown, /## 当前可进入动作确认的包/)
  assert.match(markdown, /## 目标闭环证据简表/)
  assert.match(markdown, /currentScope: backend_aliyun_only/)
  assert.match(markdown, /canProceedWithoutWechat: true/)
  assert.match(markdown, /U09_DEPLOY_AUTHORIZATION/)
  assert.match(markdown, /线上 smoke 和 404 清零验收/)
  assert.match(markdown, /blockedCredentialCount: 0/)
  assert.match(markdown, /blockedCredentialNames: none/)
  assert.match(markdown, /readySecretEnvVariableCount: 0/)
  assert.match(markdown, /resourceEvidenceReady: 7\/7/)
  assert.match(markdown, /blockedResourceEvidenceIds: none/)
  assert.match(markdown, /partiallyObservedResourceEvidenceIds: none/)
  assert.match(markdown, /readyActionPacketIds: none/)
  assert.match(markdown, /nextActionTimeConfirmations: none/)
  assert.match(markdown, /currentActionScope: image_push_or_import_and_digest_verification/)
  assert.match(markdown, /不购买 ACR/)
  assert.match(markdown, /imagePushed=true/)
  assert.match(markdown, /- deferredActions:/)
  assert.match(markdown, /不部署 production-cn/)
  assert.match(markdown, /ramLeastPrivilege=true/)
  assert.match(markdown, /- completionEvidence:/)
  assert.doesNotMatch(markdown, /必须先补齐微信开放平台移动 App 凭证/)
  assert.doesNotMatch(markdown, /requiredBlocking: .*WECHAT_OPEN_APP_ID/)
  assert.doesNotMatch(output + markdown, /sk-[A-Za-z0-9_-]{20,}/)
  assert.doesNotMatch(output + markdown, /LTAI[A-Za-z0-9]{12,}/)
  assert.doesNotMatch(output + markdown, /:\/\/[^\s:@]+:[^\s@]+@/)
})
