const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = process.cwd()
const segmentsSource = fs.readFileSync(path.join(root, "lib", "service-records", "segments.server.ts"), "utf8")
const serverSource = fs.readFileSync(path.join(root, "lib", "service-records", "server.ts"), "utf8")
const ossUploadRoute = fs.readFileSync(path.join(root, "app", "api", "mp", "service-records", "sessions", "[sessionId]", "oss-upload", "route.ts"), "utf8")
const ossSegmentRoute = fs.readFileSync(path.join(root, "app", "api", "mp", "service-records", "sessions", "[sessionId]", "segments", "oss", "route.ts"), "utf8")
const deviceFilesCheckRoute = fs.readFileSync(path.join(root, "app", "api", "mp", "service-records", "sessions", "[sessionId]", "device-files", "check", "route.ts"), "utf8")
const sessionlessDeviceFilesCheckRoute = fs.readFileSync(path.join(root, "app", "api", "mp", "service-records", "device-files", "check", "route.ts"), "utf8")

test("L12 upload routes allow appending while processing but close completed and terminal sessions", () => {
  assert.match(segmentsSource, /function serviceRecordAppendClosed\(status: unknown\)/)
  assert.match(segmentsSource, /\["completed", "failed", "cancelled"\]\.includes/)
  assert.match(ossUploadRoute, /serviceRecordAppendClosed\(session\.status\)/)
  assert.match(ossSegmentRoute, /serviceRecordAppendClosed\(session\.status\)/)
  assert.doesNotMatch(ossUploadRoute, /\["processing", "completed", "failed", "cancelled"\]/)
  assert.doesNotMatch(ossSegmentRoute, /\["processing", "completed", "failed", "cancelled"\]/)
})

test("L12 source file key can skip duplicate Bluetooth transfer and reuse uploaded audio", () => {
  assert.match(segmentsSource, /function sourceFileMetadataFromPayload/)
  assert.match(segmentsSource, /\.contains\("metadata", \{ source_file_key: key \}\)/)
  assert.match(segmentsSource, /function findReusableServiceRecordSegment/)
  assert.match(segmentsSource, /function applyReusableSegmentScope/)
  assert.match(segmentsSource, /function findReusableServiceRecordSegmentBySourceMeta/)
  assert.match(segmentsSource, /device_file_name: deviceFileName/)
  assert.match(segmentsSource, /if \(deviceFileTime\) contains\.device_file_time = deviceFileTime/)
  assert.match(segmentsSource, /if \(deviceFileSize\) contains\.device_file_size = deviceFileSize/)
  assert.match(segmentsSource, /function reusableSegmentAsrSnapshot/)

  assert.match(ossUploadRoute, /sourceFileMetadataFromPayload\(payload\)/)
  assert.match(ossUploadRoute, /findReusableServiceRecordSegment/)
  assert.match(ossUploadRoute, /findReusableServiceRecordSegmentBySourceMeta/)
  assert.match(ossUploadRoute, /let reusable = sourceMeta\.source_file_key/)
  assert.match(ossUploadRoute, /reusable = await findReusableServiceRecordSegmentBySourceMeta\(admin, session, sourceMeta\)/)
  assert.match(ossUploadRoute, /function uploadPolicyMaxBytes/)
  assert.match(ossUploadRoute, /likelyRawL12Opus/)
  assert.match(ossUploadRoute, /oggContainerSlack/)
  assert.match(ossUploadRoute, /Math\.ceil\(base \* 1\.08\) \+ 64 \* 1024/)
  assert.match(ossUploadRoute, /method: "REUSE"/)
  assert.match(ossUploadRoute, /reusable_segment: toPublicSegment\(reusable\)/)

  assert.match(ossSegmentRoute, /reused_upload/)
  assert.match(ossSegmentRoute, /findReusableServiceRecordSegmentBySourceMeta/)
  assert.match(ossSegmentRoute, /let reusable = sourceMeta\.source_file_key/)
  assert.match(ossSegmentRoute, /reusable = await findReusableServiceRecordSegmentBySourceMeta\(admin, session, sourceMeta\)/)
  assert.match(ossSegmentRoute, /reused_from_segment_id/)
  assert.match(ossSegmentRoute, /reusableSegmentAsrSnapshot/)
  assert.doesNotMatch(ossSegmentRoute, /submitServiceRecordSegmentAsr/)
  assert.match(ossSegmentRoute, /segment: toPublicSegment\(data\)/)
})

test("L12 device-files check route exposes per-file imported status before transfer", () => {
  assert.match(deviceFilesCheckRoute, /fallbackSourceFileKey/)
  assert.match(deviceFilesCheckRoute, /sourceKeyPart\(file\.device_name \|\| "L12"\)/)
  assert.doesNotMatch(deviceFilesCheckRoute, /sourceKeyPart\(file\.device_id/)
  assert.match(deviceFilesCheckRoute, /findReusableServiceRecordSegmentBySourceMeta/)
  assert.match(deviceFilesCheckRoute, /reusable = await findReusableServiceRecordSegmentBySourceMeta\(admin, session, sourceMeta\)/)
  assert.match(deviceFilesCheckRoute, /already_uploaded/)
  assert.match(deviceFilesCheckRoute, /status: alreadyUploaded \? "uploaded" : "new"/)
  assert.match(deviceFilesCheckRoute, /object_key: alreadyUploaded \? reusable\.storage_path : ""/)

  assert.match(sessionlessDeviceFilesCheckRoute, /resolveServiceRecordAuth\(request\)/)
  assert.match(sessionlessDeviceFilesCheckRoute, /company_id: ctx\.companyId \|\| null/)
  assert.match(sessionlessDeviceFilesCheckRoute, /store_id: ctx\.storeId \|\| null/)
  assert.match(sessionlessDeviceFilesCheckRoute, /user_id: ctx\.userId \|\| ""/)
  assert.match(sessionlessDeviceFilesCheckRoute, /findReusableServiceRecordSegment\(admin, scope/)
  assert.match(sessionlessDeviceFilesCheckRoute, /findReusableServiceRecordSegmentBySourceMeta\(admin, scope, sourceMeta\)/)
  assert.match(sessionlessDeviceFilesCheckRoute, /already_uploaded/)

  assert.match(serverSource, /source_file_key: cleanText\(metadata\.source_file_key/)
  assert.match(serverSource, /device_file_name: cleanText\(metadata\.device_file_name/)
  assert.match(serverSource, /reused_upload: Boolean\(metadata\.reused_upload\)/)
  assert.match(serverSource, /reused_from_segment_id: cleanText\(metadata\.reused_from_segment_id/)
})
