const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = process.cwd()
const processingSource = fs.readFileSync(path.join(root, "lib", "service-records", "processing.server.ts"), "utf8")
const sessionRouteSource = fs.readFileSync(path.join(root, "app", "api", "mp", "service-records", "sessions", "[sessionId]", "route.ts"), "utf8")
const audioRouteSource = fs.readFileSync(path.join(root, "app", "api", "mp", "service-records", "sessions", "[sessionId]", "audio", "[segmentId]", "route.ts"), "utf8")
const serverSource = fs.readFileSync(path.join(root, "lib", "service-records", "server.ts"), "utf8")
const audioEvidenceStart = processingSource.indexOf("function audioEvidenceFromSegments")
const audioEvidenceEnd = processingSource.indexOf("function buildDeepSeekMessages", audioEvidenceStart)
const audioEvidenceSource = processingSource.slice(audioEvidenceStart, audioEvidenceEnd)

test("service record v2 prompt includes business intelligence fields", () => {
  assert.match(processingSource, /"sales_opportunities"/)
  assert.match(processingSource, /"risk_warnings"/)
  assert.match(processingSource, /"missed_sales_signals"/)
  assert.match(processingSource, /"manager_brief"/)
  assert.match(processingSource, /"voice_coach_payload"/)
  assert.match(processingSource, /"evidence_timeline"/)
  assert.match(processingSource, /"customer_profile_update_suggestions"/)
  assert.match(processingSource, /销售机会必须基于转写证据或顾客档案上下文/)
  assert.match(processingSource, /business_minutes_mode=transcript_only/)
  assert.match(processingSource, /表示待确认建议，不能写成已更新事实/)
  assert.match(processingSource, /正式\/基础纪要不能只是转写摘录或流水账/)
  assert.match(processingSource, /不要把“录音已保存\/请复核转写”当成正式纪要结论/)
  assert.match(processingSource, /至少输出 1 条 customer_concerns 或 1 条 todos/)
})

test("service record v2 normalization preserves additive fields and v1 fallback", () => {
  assert.match(processingSource, /function normalizeSalesOpportunity/)
  assert.match(processingSource, /function normalizeRiskWarning/)
  assert.match(processingSource, /function normalizeManagerBrief/)
  assert.match(processingSource, /function normalizeProfileUpdateSuggestions/)
  assert.match(processingSource, /function enforceBusinessQualityGate/)
  assert.match(processingSource, /sales_opportunities: listRecordFrom\(root\.sales_opportunities/)
  assert.match(processingSource, /risk_warnings: listRecordFrom\(root\.risk_warnings/)
  assert.match(processingSource, /missed_sales_signals: listFrom\(staffReview\.missed_sales_signals/)
  assert.match(processingSource, /customer_profile_suggestions: listFrom\(/)
  assert.match(processingSource, /service_minutes_v2: serviceMinutesV2/)
  assert.match(processingSource, /employee_feedback: employeeFeedback/)
  assert.match(processingSource, /manager_review: managerReview/)
  assert.match(processingSource, /operations,/)
})

test("service record v2 keeps original audio as signed evidence instead of fake playback", () => {
  assert.match(processingSource, /function audioEvidenceFromSegments/)
  assert.match(processingSource, /audio_saved: audioEvidence\.saved/)
  assert.match(processingSource, /signed_url_required: audioEvidence\.signed_url_required/)
  assert.doesNotMatch(audioEvidenceSource, /enforceBusinessQualityGate/)
  assert.match(sessionRouteSource, /buildServiceRecordAudioEvidence/)
  assert.match(sessionRouteSource, /sessionWithAudioEvidence/)
  assert.match(audioRouteSource, /createServiceRecordSegmentAudioUrl/)
  assert.match(audioRouteSource, /getReadableServiceRecordSession/)
  assert.match(audioRouteSource, /playback_url/)
  assert.match(serverSource, /audio_available: Boolean\(row\.storage_path\)/)
  assert.match(serverSource, /storage_provider: cleanText\(metadata\.storage_provider/)
  assert.match(serverSource, /upload_source: cleanText\(metadata\.upload_source/)
  assert.match(serverSource, /audio_format_guess: cleanText\(metadata\.audio_format_guess/)
  assert.match(serverSource, /original_file_name: cleanText\(metadata\.original_file_name/)
  assert.match(serverSource, /playback_api_url/)
})

test("service record v2 local fallback uses transcript-only quality gate", () => {
  assert.match(processingSource, /const fallback = \{\s*version: "service_minutes_v2"/)
  assert.match(processingSource, /return enforceBusinessQualityGate\(fallback\)/)
  assert.match(processingSource, /sales_opportunities: \[\]/)
  assert.match(processingSource, /risk_warnings: \[\]/)
  assert.match(processingSource, /misses: \[\]/)
  assert.match(processingSource, /missed_sales_signals: \[\]/)
  assert.match(processingSource, /coaching_tips: \[\]/)
  assert.match(processingSource, /next_script: ""/)
  assert.match(processingSource, /project_interests: \[\]/)
  assert.match(processingSource, /deal_signals: \[\]/)
  assert.match(processingSource, /customer_focus: \[\]/)
  assert.match(processingSource, /staff_misses: \[\]/)
  assert.match(processingSource, /opening_script: ""/)
  assert.match(processingSource, /practice_goal: "先复核原音和转写，再决定是否进入正式训练。"/)
})

test("service record keeps smart minutes pending when DeepSeek fails instead of completing fallback as final", () => {
  assert.match(processingSource, /allowFallbackCompletion/)
  assert.match(processingSource, /smartMinutesPendingReason/)
  assert.match(processingSource, /markServiceMinutesV2PendingSmartReview/)
  assert.match(processingSource, /nextStatus = "processing"/)
  assert.match(processingSource, /智能整理失败，系统会继续重试/)
  assert.match(processingSource, /当前不是最终服务纪要/)
})
