const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = process.cwd()
const read = (...parts) => fs.readFileSync(path.join(root, ...parts), "utf8")

const endRouteSource = read("app", "api", "voice-coach", "sessions", "[sessionId]", "end", "route.ts")
const reportRouteSource = read("app", "api", "voice-coach", "sessions", "[sessionId]", "report", "route.ts")
const hintRouteSource = read("app", "api", "voice-coach", "sessions", "[sessionId]", "hint", "route.ts")
const jobsSource = read("lib", "voice-coach", "jobs.server.ts")
const llmSource = read("lib", "voice-coach", "llm.server.ts")
const refreshSource = read("lib", "voice-coach", "report-refresh.ts")
const reportServerSource = read("lib", "voice-coach", "report.server.ts")
const reportSource = read("lib", "voice-coach", "report.ts")
const sessionContextSource = read("lib", "voice-coach", "session-context.ts")
const reportWxmlSource = read("mini-program-ui", "pages", "voice-coach", "report.wxml")
const reportJsSource = read("mini-program-ui", "pages", "voice-coach", "report.js")
const chatJsSource = read("mini-program-ui", "pages", "voice-coach", "chat.js")
const setupStorageSource = read("mini-program-ui", "pages", "voice-coach", "setup-storage.js")
const sessionRouteSource = read("app", "api", "voice-coach", "sessions", "route.ts")

test("view_report and GET /report both use the shared report refresh service with snapshot fields", () => {
  assert.match(endRouteSource, /import \{ refreshVoiceCoachReport \} from "@\/lib\/voice-coach\/report-refresh"/)
  assert.match(reportRouteSource, /import \{ refreshVoiceCoachReport \} from "@\/lib\/voice-coach\/report-refresh"/)
  assert.match(endRouteSource, /if \(mode === "end_only"\)/)
  assert.match(endRouteSource, /return NextResponse\.json\(\{ ok: true \}\)/)
  assert.match(endRouteSource, /const \{ report \} = await refreshVoiceCoachReport\(\{/)
  assert.match(reportRouteSource, /const \{ report \} = await refreshVoiceCoachReport\(\{/)
  assert.match(endRouteSource, /scenario_snapshot_json/)
  assert.match(reportRouteSource, /scenario_snapshot_json/)
  assert.match(refreshSource, /maxWaitMs = 2500/)
  assert.match(refreshSource, /countPendingAnalysisJobs/)
  assert.match(refreshSource, /pumpAnalysisJobs/)
  assert.match(refreshSource, /sessionSnapshot: session\.scenario_snapshot_json/)
  assert.match(refreshSource, /sessionContext: session\.session_context_json/)
  assert.match(refreshSource, /await ops\.saveReport\(\{/)
})

test("report generation now carries snapshot-aware context review plus meta and ordered examples", () => {
  assert.match(reportSource, /training_context: VoiceCoachReportTrainingContextSchema\.optional\(\)/)
  assert.match(reportSource, /next_round_focus: VoiceCoachReportNextRoundFocusSchema\.optional\(\)/)
  assert.match(reportServerSource, /training_context: trainingContext/)
  assert.match(reportServerSource, /next_round_focus: nextRoundFocus/)
  assert.match(reportServerSource, /buildNextRoundFocus/)
  assert.match(reportServerSource, /buildTrainingContextReview/)
  assert.match(reportServerSource, /representative_turn_id/)
  assert.match(reportServerSource, /organization_example_turn_ids/)
  assert.match(reportServerSource, /pickRepresentativeTurn/)
  assert.match(reportServerSource, /pickOrganizationExamples/)
  assert.match(reportServerSource, /summary_blocks: summaryBlocks/)
  assert.match(reportServerSource, /is_complete:/)
})

test("report-related schema contracts are tightened and context-aware fallbacks stay on scenario", () => {
  assert.match(llmSource, /polished: z\.string\(\)\.min\(40\)\.max\(220\)/)
  assert.match(jobsSource, /const normalizedNextCustomerTag = normalizeScenarioTag\(nextCustomer\.tag, scenario\)/)
  assert.match(jobsSource, /features_json: \{ tag: normalizedNextCustomerTag \}/)
  assert.match(jobsSource, /sessionSnapshot: loaded\.session\.scenario_snapshot_json/)
  assert.match(hintRouteSource, /sessionSnapshot: session\.scenario_snapshot_json/)
  assert.match(hintRouteSource, /getVoiceCoachSessionInsights/)
  assert.match(sessionRouteSource, /features_json: \{ tag: normalizeScenarioTag\(first\.tag, scenario\) \}/)
})

test("follow-up second-round training carries source session through client and server", () => {
  assert.match(sessionContextSource, /followup_context:\s*z/)
  assert.match(sessionContextSource, /normalizeVoiceCoachFollowupContext/)
  assert.match(sessionContextSource, /buildVoiceCoachFollowupOpening/)
  assert.match(sessionContextSource, /上一轮复盘重点/)
  assert.match(sessionRouteSource, /loadFollowupContext/)
  assert.match(sessionRouteSource, /\.eq\("user_id", args\.userId\)/)
  assert.match(sessionRouteSource, /source_report_not_found/)
  assert.match(sessionRouteSource, /buildVoiceCoachFollowupOpening\(sessionSnapshot\)/)
  assert.match(setupStorageSource, /normalizeFollowupContext/)
  assert.match(setupStorageSource, /followup_context: followupContext/)
  assert.match(reportJsSource, /savePendingVoiceCoachSetup/)
  assert.match(reportJsSource, /source_session_id: sessionId/)
  assert.match(chatJsSource, /payload\.followup_context/)
  assert.ok(reportWxmlSource.includes("按这个重点再练一轮"))
})

test("report page copy still exposes the same coaching review structure", () => {
  assert.ok(reportWxmlSource.includes("训练完成 · 评测档案"))
  assert.ok(reportWxmlSource.includes("训练背景"))
  assert.ok(reportWxmlSource.includes("五维度表现"))
  assert.ok(reportWxmlSource.includes("训练总结"))
  assert.ok(reportWxmlSource.includes("逐项拆解"))
})
