const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const root = process.cwd()
const metricsSource = fs.readFileSync(path.join(root, "lib", "voice-coach", "metrics.ts"), "utf8")
const llmSource = fs.readFileSync(path.join(root, "lib", "voice-coach", "llm.server.ts"), "utf8")
const jobsSource = fs.readFileSync(path.join(root, "lib", "voice-coach", "jobs.server.ts"), "utf8")
const chatSource = fs.readFileSync(path.join(root, "mini-program-ui", "pages", "voice-coach", "chat.js"), "utf8")
const chatWxmlSource = fs.readFileSync(path.join(root, "mini-program-ui", "pages", "voice-coach", "chat.wxml"), "utf8")
const reportServerSource = fs.readFileSync(path.join(root, "lib", "voice-coach", "report.server.ts"), "utf8")
const reportJsSource = fs.readFileSync(path.join(root, "mini-program-ui", "pages", "voice-coach", "report.js"), "utf8")
const reportWxmlSource = fs.readFileSync(path.join(root, "mini-program-ui", "pages", "voice-coach", "report.wxml"), "utf8")
const wsProtocolSource = fs.readFileSync(path.join(root, "voice-coach-ws", "src", "protocol.ts"), "utf8")
const wsPromptSource = fs.readFileSync(path.join(root, "voice-coach-ws", "src", "shared", "prompts.ts"), "utf8")
const wsOrchestratorSource = fs.readFileSync(path.join(root, "voice-coach-ws", "src", "pipeline", "orchestrator.ts"), "utf8")

test("http analysis pipeline keeps five-dimension per-turn scores wired end to end", () => {
  assert.match(metricsSource, /export function computePerTurnScores/)
  assert.match(llmSource, /persuasion_score: z\.number\(\)\.min\(0\)\.max\(100\)\.optional\(\)/)
  assert.match(llmSource, /organization_score: z\.number\(\)\.min\(0\)\.max\(100\)\.optional\(\)/)
  assert.match(llmSource, /"persuasion_score": number/)
  assert.match(llmSource, /"organization_score": number/)
  assert.match(jobsSource, /analysis\.per_turn_scores = computePerTurnScores\(\{/)
  assert.match(jobsSource, /llmPersuasion: analysis\.persuasion_score/)
  assert.match(jobsSource, /llmOrganization: analysis\.organization_score/)
})

test("chat suggestions normalize highlight severity, preserve zero scores and keep loading state", () => {
  assert.match(chatSource, /function normalizeHighlightSeverity/)
  assert.match(chatSource, /if \(raw === 'warning'\) return 'warn'/)
  assert.match(chatSource, /if \(raw === 'danger'\) return 'bad'/)
  assert.match(chatSource, /typeof rawScore === 'number' && isFinite\(rawScore\)/)
  assert.ok(chatWxmlSource.includes('class="suggest-loading"'))
  assert.ok(chatWxmlSource.includes("item.analysis.risk_notes"))
})

test("report generation only exposes data-backed curves and report ui renders dynamic charts", () => {
  assert.match(reportServerSource, /id: "speech_rate_curve"/)
  assert.match(reportServerSource, /id: "filler_ratio_curve"/)
  assert.match(reportServerSource, /id: "clarity_curve"/)
  assert.ok(!reportServerSource.includes("pause_curve"))
  assert.ok(!reportServerSource.includes("pitch_curve"))
  assert.match(reportServerSource, /points: wpmCurve/)
  assert.match(reportServerSource, /points: fillerCurve/)
  assert.match(reportServerSource, /points: clarityCurve/)
  assert.match(reportJsSource, /activeTabIndex/)
  assert.match(reportJsSource, /canvas_id: `\$\{prefix\}Chart\$\{index \+ 1\}`/)
  assert.match(reportJsSource, /syncCanvasMetrics\(\)/)
  assert.match(reportJsSource, /radarCanvasSize/)
  assert.match(reportJsSource, /lineChartWidth/)
  assert.match(reportJsSource, /lineChartHeight/)
  assert.doesNotMatch(reportJsSource, /ctx\.scale\(dpr,\s*dpr\)/)
  assert.ok(reportWxmlSource.includes('class="tab-indicator"'))
  assert.ok(reportWxmlSource.includes('class="score-card-top"'))
  assert.ok(reportWxmlSource.includes('class="dim-row-top"'))
  assert.ok(reportWxmlSource.includes('class="dim-score-pill"'))
  assert.ok(reportWxmlSource.includes('class="summary-title"'))
  assert.ok(reportWxmlSource.includes('class="linechart-card"'))
  assert.ok(reportWxmlSource.includes('class="linechart-canvas"'))
  assert.ok(reportWxmlSource.includes('canvas-id="{{item.canvas_id}}"'))
  assert.ok(reportWxmlSource.includes('class="chart-empty"'))
})

test("ws analysis contract keeps scores and normalized severity semantics", () => {
  assert.match(wsProtocolSource, /per_turn_scores: z\.record\(z\.string\(\), z\.number\(\)\)\.optional\(\)/)
  assert.match(wsProtocolSource, /severity: z\.enum\(\["info", "warn", "bad", "warning", "danger"\]\)/)
  assert.match(wsPromptSource, /"persuasion_score": number/)
  assert.match(wsPromptSource, /"organization_score": number/)
  assert.match(wsOrchestratorSource, /analysis\.per_turn_scores = computePerTurnScores\(\{/)
  assert.match(wsOrchestratorSource, /case "warn":\s*return "warning"/)
  assert.match(wsOrchestratorSource, /case "bad":\s*return "danger"/)
})
