import type { DeliveryPackInput, DeliveryPackOutput } from "./schema"

export const samplePackId = "sample-pack"

export const sampleDeliveryPackInput: DeliveryPackInput = {
  team_type: "agency",
  team_size: "4-8",
  industry: "beauty",
  platform: "xiaohongshu",
  offer_type: "训练营",
  offer_desc: "小红书爆款内容训练营",
  delivery_mode: "线上陪跑",
  sop_level: "一般",
  guideline_level: "一般",
  current_problem: ["流量低", "转化低"],
  topic_library: "零散",
  multi_project: "多项目并行",
  script_review: "返工多",
  qc_process: "缺少质检",
  conversion_path: "引导评论领取资料",
  review_frequency: "每周复盘",
  product_or_service: "内容增长服务",
  target_audience: "中小企业主",
  price_range: "¥2999-6999",
  tone: "专业但接地气",
}

export const sampleDeliveryPackOutput: DeliveryPackOutput = {
  meta: {
    industry: "beauty",
    platform: "xiaohongshu",
    team_type: "agency",
    offer_desc: "小红书爆款内容训练营",
  },
  bottleneck: "选题与转化链路脱节，导致流量有但成交弱。",
  top_actions: [
    {
      title: "先锁定3个高意图场景",
      why: "高意图场景能直接带来私信与评论线索。",
      do_in_7_days: ["锁定3个高频场景", "每个场景产出2条标题", "第7天复盘成交数据"],
    },
    {
      title: "固定7天排产节奏",
      why: "减少临时选题与改稿，提高发布稳定性。",
      do_in_7_days: ["用4X4配比排出7天", "第1天先跑爆款结构", "第4天补一条转化脚本"],
    },
    {
      title: "搭建CTA合规清单",
      why: "避免触发平台限制，提升评论转化。",
      do_in_7_days: ["统一CTA口径", "建立评论回复模板", "每条脚本上线前自检"],
    },
  ],
  scores: [
    { dimension: "定位", score: 62, insight: "定位描述偏泛", fix: "强化差异化标签" },
    { dimension: "内容", score: 58, insight: "标题密度不足", fix: "补齐人群/价格/场景" },
    { dimension: "情绪", score: 71, insight: "情绪点完整", fix: "增加行动指令" },
    { dimension: "转化", score: 48, insight: "CTA不够聚焦", fix: "统一评论领取口径" },
    { dimension: "运营", score: 57, insight: "排产节奏不稳", fix: "固定7天排产模板" },
  ],
  tomorrow_post: {
    title: "小红书爆款·中小企业主｜¥2999档最容易跑通的内容结构",
    body:
      "如果你是中小企业主，做小红书最怕的是“有流量没咨询”。这条内容给你一个可直接复用的结构：先用一个具体场景拉起共鸣，再抛出一个对比结论，最后给到3步执行清单。今天先把标题和钩子跑通，评论区回复【方案】领取完整模板。",
    pinned_comment: "评论区回复【方案】领取完整模板",
    cover_text: "¥2999档内容结构",
  },
  calendar_7d: [
    {
      day: 1,
      type: "引流",
      title: "小红书·中小企业主｜¥2999档内容结构怎么排",
      hook: "有流量没咨询？先从结构改起",
      outline: ["场景痛点", "结构拆解", "执行清单"],
      cta: "评论区回复【方案】领取模板",
      script_id: "S1",
    },
    {
      day: 2,
      type: "建信",
      title: "小红书·中小企业主｜训练营如何避免返工",
      hook: "返工不是勤快，是流程没锁住",
      outline: ["返工成本", "流程拆解", "模板示例"],
      cta: "评论区回复【清单】领取质检表",
      script_id: "S2",
    },
    {
      day: 3,
      type: "引流",
      title: "小红书·中小企业主｜¥2999档客户最常问3件事",
      hook: "你不回答，竞争对手会回答",
      outline: ["常见问题", "快速回答", "引导行动"],
      cta: "评论区回复【方案】领取模板",
      script_id: "S1",
    },
    {
      day: 4,
      type: "转化",
      title: "小红书·中小企业主｜训练营转化话术怎么写",
      hook: "一句话把价值说清楚",
      outline: ["核心价值", "对比差异", "下一步"],
      cta: "评论区回复【话术】领取模板",
      script_id: "S3",
    },
    {
      day: 5,
      type: "建信",
      title: "小红书·中小企业主｜排产节奏如何稳住",
      hook: "排产不稳，交付一定乱",
      outline: ["节奏问题", "排产示例", "执行提醒"],
      cta: "评论区回复【日历】领取排产表",
      script_id: "S2",
    },
    {
      day: 6,
      type: "引流",
      title: "小红书·中小企业主｜¥2999档选题库怎么做",
      hook: "先有题，再谈爆",
      outline: ["题库结构", "高意图标签", "落地示例"],
      cta: "评论区回复【选题】领取清单",
      script_id: "S1",
    },
    {
      day: 7,
      type: "转化",
      title: "小红书·中小企业主｜训练营成交的最后一问",
      hook: "客户犹豫时，你要给出下一步",
      outline: ["犹豫点", "解决方案", "行动引导"],
      cta: "评论区回复【方案】领取模板",
      script_id: "S3",
    },
  ],
  topics_10: [
    {
      title: "¥2999档训练营最容易卡住的3个环节",
      audience: "中小企业主",
      scene: "启动训练营前",
      pain: "流程不清晰",
      keywords: ["排产", "模板"],
      type: "拆解",
      cta: "评论区回复【方案】领取模板",
    },
    {
      title: "小红书内容交付的3条红线",
      audience: "中小企业主",
      scene: "交付复盘",
      pain: "合规风险",
      keywords: ["合规", "质检"],
      type: "提醒",
      cta: "评论区回复【清单】领取质检表",
    },
    {
      title: "训练营转化最关键的一句话",
      audience: "中小企业主",
      scene: "咨询转化",
      pain: "转化慢",
      keywords: ["转化", "话术"],
      type: "技巧",
      cta: "评论区回复【话术】领取模板",
    },
    {
      title: "如何用7天排产把交付跑顺",
      audience: "中小企业主",
      scene: "内容规划",
      pain: "节奏不稳",
      keywords: ["排产", "节奏"],
      type: "方法",
      cta: "评论区回复【日历】领取排产表",
    },
    {
      title: "选题库从0到1的3步法",
      audience: "中小企业主",
      scene: "选题搭建",
      pain: "选题不足",
      keywords: ["选题", "题库"],
      type: "方法",
      cta: "评论区回复【选题】领取清单",
    },
    {
      title: "小红书标题密度不够怎么办",
      audience: "中小企业主",
      scene: "内容优化",
      pain: "曝光低",
      keywords: ["标题", "密度"],
      type: "技巧",
      cta: "评论区回复【方案】领取模板",
    },
    {
      title: "训练营客户最关心的三件事",
      audience: "中小企业主",
      scene: "客户沟通",
      pain: "信任不足",
      keywords: ["客户", "需求"],
      type: "洞察",
      cta: "评论区回复【方案】领取模板",
    },
    {
      title: "脚本返工多的根因是什么",
      audience: "中小企业主",
      scene: "交付复盘",
      pain: "返工成本",
      keywords: ["脚本", "返工"],
      type: "拆解",
      cta: "评论区回复【清单】领取质检表",
    },
    {
      title: "内容交付团队的SOP最小闭环",
      audience: "中小企业主",
      scene: "流程搭建",
      pain: "流程缺失",
      keywords: ["SOP", "流程"],
      type: "方法",
      cta: "评论区回复【方案】领取模板",
    },
    {
      title: "用一个案例讲清楚训练营价值",
      audience: "中小企业主",
      scene: "价值表达",
      pain: "表达不清",
      keywords: ["案例", "价值"],
      type: "案例",
      cta: "评论区回复【方案】领取模板",
    },
  ],
  scripts_3: [
    {
      id: "S1",
      type: "引流",
      duration: "60-90秒",
      shots: [
        { t: "0-3s", line: "有流量没咨询？先把结构改对", visual: "镜头对准痛点关键词" },
        { t: "3-20s", line: "这套结构适合¥2999档训练营", visual: "展示结构三步" },
        { t: "20-50s", line: "场景→结论→行动清单", visual: "卡片式拆解" },
      ],
      cta: "评论区回复【方案】领取模板",
      title_options: ["训练营结构怎么排", "¥2999档内容结构", "有流量没咨询怎么办"],
      pinned_comment: "评论区回复【方案】领取模板",
    },
    {
      id: "S2",
      type: "建信",
      duration: "60-90秒",
      shots: [
        { t: "0-3s", line: "返工多的根因不是人，是流程", visual: "镜头切流程图" },
        { t: "3-25s", line: "用质检清单锁口径", visual: "清单弹窗" },
        { t: "25-50s", line: "每条脚本上线前自检", visual: "打勾动作" },
      ],
      cta: "评论区回复【清单】领取质检表",
      title_options: ["返工多怎么办", "质检清单怎么做", "交付流程如何稳"],
      pinned_comment: "评论区回复【清单】领取质检表",
    },
    {
      id: "S3",
      type: "转化",
      duration: "60-90秒",
      shots: [
        { t: "0-3s", line: "客户犹豫时，你要给出下一步", visual: "镜头对准CTA" },
        { t: "3-20s", line: "一句话说明价值+行动", visual: "话术卡片" },
        { t: "20-50s", line: "统一评论领取口径", visual: "评论区示意" },
      ],
      cta: "评论区回复【话术】领取模板",
      title_options: ["训练营成交话术", "转化最后一问", "客户犹豫怎么办"],
      pinned_comment: "评论区回复【话术】领取模板",
    },
  ],
  qc_checklist: {
    title: ["标题包含人群/价格/场景", "避免绝对化承诺", "关键词密度≥2"],
    body: ["结构至少3段", "结尾有行动指令", "数据来源注明"],
    cta_and_compliance: ["统一评论领取口径", "避免外链导流", "不出现联系方式"],
  },
  archive_rules: {
    naming: "行业_场景_日期_脚本编号",
    tags: ["行业", "人群", "阶段"],
    dedupe: ["检查选题库", "标记重复标题", "每周复盘清理"],
  },
  upsell: {
    when_to_upgrade: ["需要更多脚本产能时", "团队需要多人协作时"],
    cta: "进入内容工坊，持续生成可用脚本",
  },
}
